# Generated by Django 3.1.7 on 2021-03-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210309_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='first',
            new_name='matkul',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='last',
        ),
    ]
